import jsPDF from 'jspdf';

interface InvoiceData {
  invoiceNumber: string;
  date: string;
  dueDate: string;
  clientName: string;
  clientEmail: string;
  clientAddress: string;
  items: Array<{
    description: string;
    quantity: number;
    rate: number;
    amount: number;
  }>;
  subtotal: number;
  tax: number;
  total: number;
  notes: string;
}

export const generatePDF = async (invoiceData: InvoiceData) => {
  const pdf = new jsPDF();
  
  // Set font
  pdf.setFont('helvetica');
  
  // Header
  pdf.setFontSize(24);
  pdf.setTextColor(59, 130, 246); // Blue color
  pdf.text('INVOICE', 105, 30, { align: 'center' });
  
  pdf.setFontSize(12);
  pdf.setTextColor(100, 100, 100);
  pdf.text(`#${invoiceData.invoiceNumber}`, 105, 40, { align: 'center' });
  
  // Reset color to black
  pdf.setTextColor(0, 0, 0);
  
  // Company info (placeholder)
  pdf.setFontSize(10);
  pdf.text('From:', 20, 60);
  pdf.text('Your Company Name', 20, 70);
  pdf.text('Your Address', 20, 80);
  pdf.text('City, State ZIP', 20, 90);
  
  // Client info
  pdf.text('To:', 120, 60);
  pdf.text(invoiceData.clientName || 'Client Name', 120, 70);
  pdf.text(invoiceData.clientEmail || 'client@email.com', 120, 80);
  
  // Split address into lines
  const addressLines = (invoiceData.clientAddress || 'Client Address').split('\n');
  addressLines.forEach((line, index) => {
    pdf.text(line, 120, 90 + (index * 10));
  });
  
  // Dates
  pdf.text(`Invoice Date: ${invoiceData.date}`, 20, 120);
  pdf.text(`Due Date: ${invoiceData.dueDate || 'Not specified'}`, 120, 120);
  
  // Table header
  const startY = 140;
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  
  pdf.text('Description', 20, startY);
  pdf.text('Qty', 120, startY, { align: 'center' });
  pdf.text('Rate', 140, startY, { align: 'right' });
  pdf.text('Amount', 180, startY, { align: 'right' });
  
  // Table line
  pdf.line(20, startY + 5, 190, startY + 5);
  
  // Table items
  pdf.setFont('helvetica', 'normal');
  let currentY = startY + 15;
  
  invoiceData.items.forEach((item) => {
    pdf.text(item.description || 'Item description', 20, currentY);
    pdf.text(item.quantity.toString(), 120, currentY, { align: 'center' });
    pdf.text(`₹${item.rate.toFixed(2)}`, 140, currentY, { align: 'right' });
    pdf.text(`₹${item.amount.toFixed(2)}`, 180, currentY, { align: 'right' });
    currentY += 10;
  });
  
  // Totals
  const totalsY = currentY + 10;
  pdf.line(120, totalsY, 190, totalsY);
  
  pdf.text('Subtotal:', 140, totalsY + 10, { align: 'right' });
  pdf.text(`₹${invoiceData.subtotal.toFixed(2)}`, 180, totalsY + 10, { align: 'right' });
  
  pdf.text(`Tax (${invoiceData.tax}%):`, 140, totalsY + 20, { align: 'right' });
  pdf.text(`₹${((invoiceData.subtotal * invoiceData.tax) / 100).toFixed(2)}`, 180, totalsY + 20, { align: 'right' });
  
  pdf.setFont('helvetica', 'bold');
  pdf.text('Total:', 140, totalsY + 30, { align: 'right' });
  pdf.text(`₹${invoiceData.total.toFixed(2)}`, 180, totalsY + 30, { align: 'right' });
  
  // Notes
  if (invoiceData.notes) {
    pdf.setFont('helvetica', 'normal');
    pdf.text('Notes:', 20, totalsY + 50);
    
    // Split notes into multiple lines if needed
    const noteLines = pdf.splitTextToSize(invoiceData.notes, 170);
    pdf.text(noteLines, 20, totalsY + 60);
  }
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(100, 100, 100);
  pdf.text('Generated by InvoiceR - Professional Invoice Generator', 105, 280, { align: 'center' });
  
  // Save the PDF
  pdf.save(`${invoiceData.invoiceNumber}.pdf`);
};